software_packages:
  - name: qemu-guest-agent
    version: latest
  - name: htop
    version: latest
  - name: tuned
    version: latest    
  - name: curl
    version: latest   
  - name: net-tools
    version: latest
  - name: neovim
    version: latest
  - name: unzip
    version: latest
  - name: sysstat
    version: latest
  - name: iotop
    version: latest
  - name: sysstat
    version: latest
  - name: iftop
    version: latest
