---
- name: practice with_item looping
  hosts: localhost
  become: true
  tasks:
    - name: create users
      ansible.builtin.user:
        name: "{{ item }}"
      with_items:
        - sam
        - bob
        - john
